Django_Level_Four/learning_templates/basicApp/urls.py
from django.conf.urls import url
from basicApp import views


#Template tagging

app_name = 'basicApp'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

Django_Level_Four/learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicApp import views


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basicApp/',include('basicApp.urls'))
]

Django_Level_Four/learning_templates/basicApp/models.py
from django.db import models

# Create your models here.

Django_Level_Four/learning_templates/basicApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request,'basicApp/index.html',context_dict)

def other(request):
    return render(request,'basicApp/other.html')

def relative(request):
    return render(request,'basicApp/relative_url_templates.html')

Django_Level_Four/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">


</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a> </li>
                <li><a class="navbar-link" href="{% url 'basicApp:other' %}">OTHER</a> </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
<!--        Anything outside of this will be inherited if you extend!-->
        {% endblock %}
    </div>
</body>
</html>

Django_Level_Four/templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
    {% block body_block %}
    <h1>Welcome to index</h1>
<!--    <h2>This is index.html page showing!</h2>-->
    <h2>{{ text|cut:'world' }}
        {{ number|add:"99" }}</h2>
    {% endblock %}

Django_Level_Four/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
    {% block body_block %}
    <h1>Welcome to OTHER</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

Django_Level_Four/templates/basicApp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basicApp:other' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Link to Admin</a>
    <a href = "{% url 'index' %}">Link to index!</a>
</body>
</html>